### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by jeremy-dobler** [ThorstenHans/electron-es2015-ng2#1]
Hey,

I love this app. It is exactly what I have been looking for with regards to configuration, language, along with other reasons. Do you have a way to run/debug this app without building it to the exe file? I have tried "electron ./src/main/index.js" from the main directory and "electron ./main/index.js" from the dist/ directory but that doesn't quite work.

**Comment by ThorstenHans** [comment]
Hey, you mean debugging the main proc or the renderer, when it comes to the SPA we normally develop and debug using a dedicated gulp task focusing only the web. 

Take a look at the BoardZ Repo over here https://github.com/ThorstenHans/boardz-cross-platform-sample

If you're interested in debugging the main process, take a look at the electron docs, it's explained in detail over there

**Comment by jeremy-dobler** [comment]
Awesome, thanks. Yea I was specifically looking into the web side of it, but the electron gulp tasks will be handy too. I will look into those gulp tasks.

**Comment by ThorstenHans** [comment]
Okay, hope that helps ;)
